### ISSUE TITLE
check_ctf error

### ISSUE THREAD

**Issue by Autostone-c** [tier4/caret#104]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [X] I've read [document](https://tier4.github.io/CARET_doc/main/) and no solution were found.

### Step where the question is related to

Visualization

### Description

when i run (ros2 caret check_ctf -d ~/ros2_ws/evaluate/e2e_sample/) i meet error
![image](https://github.com/tier4/caret/assets/50130211/a51f8ca8-bb12-4b83-941e-341dff0af9a0)

**Comment by takeshi-iwanari** [comment]
Please install pandas < 2.1.0
See https://github.com/tier4/CARET_analyze/pull/324 for more detail.

**Comment by Autostone-c** [comment]
> Please install pandas < 2.1.0 See [tier4/CARET_analyze#324](https://github.com/tier4/CARET_analyze/pull/324) for more detail.

thanks for this help. 
and i also want to ask if i can move all caret.repos packages to humble（replace rclcpp ros2_tracing and add the othes packages） and compile by manually。then i only source humble/install/setup.bash to recording？

**Comment by takeshi-iwanari** [comment]
> and i also want to ask if i can move all caret.repos packages to humble（replace rclcpp ros2_tracing and add the othes packages） and compile by manually。then i only source humble/install/setup.bash to recording？

I didn't try it but it seems a good idea! I think it's worth a try.

**Comment by Autostone-c** [comment]
> > and i also want to ask if i can move all caret.repos packages to humble（replace rclcpp ros2_tracing and add the othes packages） and compile by manually。then i only source humble/install/setup.bash to recording？
> 
> I didn't try it but it seems a good idea! I think it's worth a try.

thanks，i will try it. and close this issues
