### ISSUE TITLE
Failed to find trace point added by caret-rclcpp v0.4.9 -> v0.4.10

### ISSUE THREAD

**Issue by Tobias-Pe** [tier4/caret#96]
### Checklist

- [X] I've read the [contribution guidelines](https://github.com/tier4/caret/blob/main/.github/CONTRIBUTING.md).
- [X] I've read [document](https://tier4.github.io/CARET_doc/main/) and no solution were found.

### Issue type

Bug

### Step where the issue is related to

Recording

### Environments

- Docker Base-Image: osrf/ros:humble-desktop

### CARET version

CARET: v0.4.10

### Description

Since the update from v04.9 to v0.4.10 i can't visualize my recorded data

After Building i always check with `ros2 caret check_caret_rclcpp` my workspace:

```
Summary: 26 packages finished [3.53s]
INFO    : 2023-06-16 15:52:36 | All packages are built using caret-rclcpp.
```

But when running `lttng = Lttng("./" + trace_name)` in my jupyternotebook it returns the warning:

```
Failed to find trace point added by caret-rclcpp. To check whether binary are built with caret-rclcpp,run CARET CLI : ros2 caret check_caret_rclcpp.
```

ros2 caret check_ctf -d <path-to-trace-data> returns the same warning

`plot = Plot.create_frequency_timeseries_plot(app.communications)` is showing nothing and the path plots are throwing an error about zero size array.

**Going from main branch to `v0.4.9` fixed that issue for me.**

I tried to (record as the manual says)[https://tier4.github.io/CARET_doc/main/recording/recording/] but neither Starting LTTng session manually nor Starting LTTng session via ROS launch changed the failing verfication of the data after recording.

### Steps to reproduce

see description

### LTTng trace log file

![image](https://github.com/tier4/caret/assets/49952224/88519db0-217c-4f62-b43c-c365bd5e0d85)

[launch_traces.zip](https://github.com/tier4/caret/files/11771120/launch_traces.zip)

**Comment by nabetetsu** [comment]
@Tobias-Pe Thank you for your reporting.

What version of caret did you use to acquire the data you are trying to analyze with caret_analyze?
Although v0.4.10 includes modifications that affect compatibility of analysis data, but it is expected that both old and new data can be analyzed with CARET_analyze v0.4.10.
We will investigate the data you provided.

**Comment by takeshi-iwanari** [comment]
The shared trace date looks recorded with light option. Since v0.4.10, the new trace point is used and filter setting for light option needs to be modified.

If you record via launch file, please add `ros2:rmw_take` to the filter setting. Please refer to the updated instruction in [this PR](https://github.com/tier4/CARET_doc/pull/196) (Sorry, it's not merged yet.)

The filter setting for light option in `ros2 caret record` command is already updated in v0.4.10. So, you should face the problem when you manually start LTTng session using the `ros2 caret record` command. Please confirm the version of `~/ros2_caret_ws/src/CARET/ros2caret/` is v0.4.10 as well.

**Comment by Tobias-Pe** [comment]
@nabetetsu the one that gets verified was recorded on 0.4.9
The other two on 0.4.10

**Comment by Tobias-Pe** [comment]
> @Tobias-Pe 
> The shared trace date looks recorded with light option. Since v0.4.10, the new trace point is used and filter setting for light option needs to be modified.
> 
> If you record via launch file, please add `ros2:rmw_take` to the filter setting. Please refer to the updated instruction in [this PR](https://github.com/tier4/CARET_doc/pull/196) (Sorry, it's not merged yet.)
> 
> The filter setting for light option in `ros2 caret record` command is already updated in v0.4.10. So, you should face the problem when you manually start LTTng session using the `ros2 caret record` command. Please confirm the version of `~/ros2_caret_ws/src/CARET/ros2caret/` is v0.4.10 as well.

@takeshi-iwanari 

I'll try this, but I also tried to set caret_light variable to False in the provided advanced script, and it didn't work either. I also tried to trace manually, and that also didn't work.

**Comment by takeshi-iwanari** [comment]
@Tobias-Pe 
Thank you for sharing the details. Hmm, it's weird..
Could you also share the trace date where caret_light=False? So that we can ignore caret_light case and it makes our investigation easier.

**Comment by Tobias-Pe** [comment]
![image](https://github.com/tier4/caret/assets/49952224/1c2783ca-b9e0-4600-8e34-8f6887de59e0)

![image](https://github.com/tier4/caret/assets/49952224/aa95ad1a-ca2c-48bf-aa48-efb657f181eb)

[launch_trace.zip](https://github.com/tier4/caret/files/11788723/launch_trace.zip)

My Launchfile, which you can use to launch other launchfiles via launchfile_arg:

```python
# source: https://tier4.github.io/CARET_doc/latest/recording/recording/#advanced-useful-settings-for-launch-file

import launch
import launch_ros.actions
from tracetools_launch.action import Trace
from launch.actions import IncludeLaunchDescription, DeclareLaunchArgument
from launch.launch_description_sources import PythonLaunchDescriptionSource
from launch.substitutions import LaunchConfiguration

import sys
import datetime
from distutils.util import strtobool
import os


def generate_launch_description():
    caret_session = ""
    caret_event = ["ros2*"]
    caret_light = False

    for arg in sys.argv:
        if arg.startswith("caret_session:="):
            caret_session = arg.split(":=")[1]
        elif arg.startswith("caret_light:="):
            try:
                caret_light = strtobool(arg.split(":=")[1])  # 0 or 1
            except:
                print("Invalid arguments 'caret_light'.")
                print("Start tracing with 'ros2*'.")

    if caret_light:
        caret_event = [
            "ros2:*callback*",
            "ros2_caret:*callback*",
            "ros2:dispatch*",
            "ros2_caret:dispatch*",
            "ros2:rclcpp*",
            "ros2_caret:rclcpp*",
            "ros2_caret:rmw*",
            "*callback_group*",
            "ros2_caret:*executor",
            "ros2_caret:dds_bind*",
            "ros2:rcl_*init",
            "ros2_caret:rcl_*init",
            "ros2_caret:caret_init",
        ]

    if caret_session == "":
        dt_now = datetime.datetime.now()
        caret_session = "launch_trace_" + dt_now.strftime("%Y%m%d-%H%M%S")

    log_level = LaunchConfiguration("log_level")
    log_level_arg = DeclareLaunchArgument(
        "log_level",
        default_value=["INFO"],
        description="Logging level",
    )
    launchfile = LaunchConfiguration("launchfile")
    launchfile_arg = DeclareLaunchArgument(
        "launchfile",
        default_value=os.environ.get("ROS_HOME") + "/launch/aadc.py",
        description="The to be traced launch-configuration",
    )
    return launch.LaunchDescription(
        [
            log_level_arg,
            launchfile_arg,
            Trace(session_name=caret_session, events_kernel=[], events_ust=caret_event),
            # Start Launchfile
            IncludeLaunchDescription(
                PythonLaunchDescriptionSource([launchfile]),
                launch_arguments={
                    "log_level": log_level,
                }.items(),
            ),
        ]
    )

```

**Comment by Tobias-Pe** [comment]
@takeshi-iwanari 

Hope this helps you more :)

**Comment by takeshi-iwanari** [comment]
@Tobias-Pe 
The following warning is our mistake. The trace point list used in `check_ctf` command should have been updated at v0.4.10. We will fix it soon.

> Failed to find trace point added by caret-rclcpp. To check whether binary are built with caret-rclcpp,run CARET CLI : ros2 caret check_caret_rclcpp.

However, it's just a warning. So please ignore it and keep going to visualization process.
When I visualize communications using `launch_trace_light_on`, I got a similar one with `launch_trace_20230615-193736` which I think you recorded using CARET v0.4.9. 

- launch_trace_20230615-193736 (v0.4.9)
  - ![image](https://github.com/tier4/caret/assets/105265012/0d476d39-8d2a-4eff-857b-fe16e4b41569)
- launch_trace_light_off (v0.4.10 + caret_light=off)
  - ![image](https://github.com/tier4/caret/assets/105265012/ed6b237d-0ab0-4d38-a984-b13400746475)
- launch_trace_light_on (v0.4.10 + caret_light=on)
  - comunication graph is empty, but it's as expected because the event filter is not updated
  - ![image](https://github.com/tier4/caret/assets/105265012/81a87287-22f0-4645-a29f-c36cb4c7ed9c)

**Comment by Tobias-Pe** [comment]
> @Tobias-Pe 
> The following warning is our mistake. The trace point list used in `check_ctf` command should have been updated at v0.4.10. We will fix it soon.
> 
> > Failed to find trace point added by caret-rclcpp. To check whether binary are built with caret-rclcpp,run CARET CLI : ros2 caret check_caret_rclcpp.
> 
> So please ignore the warning and move on to visualization process. When I visualize communications for `launch_trace_light_off`, I got a similar one with `launch_trace_20230615-193736` which I think you recorded using CARET v0.4.9. I also attach the jupyter notebook script I tested. [issue_096.zip](https://github.com/tier4/caret/files/11816177/issue_096.zip)
> 
> - launch_trace_20230615-193736 (v0.4.9)
>   - ![image](https://github.com/tier4/caret/assets/105265012/0d476d39-8d2a-4eff-857b-fe16e4b41569)
> - launch_trace_light_off (v0.4.10 + caret_light=off)
>   - ![image](https://github.com/tier4/caret/assets/105265012/11dc23e9-0a28-4f5b-8bc2-57d071cc5af3)
> - launch_trace_light_on (v0.4.10 + caret_light=on)
>   - communication graph is empty, but it's as expected because the event filter is not updated
>   - ![image](https://github.com/tier4/caret/assets/105265012/81a87287-22f0-4645-a29f-c36cb4c7ed9c)
> 
> 
> 
> 

Yeah works 

Fine then it's okay :)
